export const dummyProperties = [
  {
    id: "1",
    title: "Modern Luxury Apartment",
    location: "Manhattan, New York",
    price: 2500,
    type: "Apartment",
    status: "rent",
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    featured: true,
    image: "/images/image1.jpg",
    description:
      "A stunning Luxury Apartment located in the heart of Manhattan, offering breathtaking views of the city skyline. This spacious apartment features modern amenities, high-end finishes, and a prime location close to shopping, dining, and entertainment options.",
  },
  {
    id: "2",
    title: "Contemporary Family Villa",
    location: "Beverly Hills, Los Angeles",
    price: 850000,
    type: "Villa",
    status: "sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    featured: true,
    image: "/images/image2.jpg",
    description:
      "Beautiful contemporary villa featuring elegant architecture, large ",
  },
  {
    id: "3",
    title: "Minimalist Smart Home",
    location: "Tokyo, Japan",
    price: 4200,
    type: "Smart Home",
    status: "rent",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    featured: false,
    image: "/images/image3.jpg",
    description:
      "Fully automated smart home with premium finishes, floor-to-ceiling w",
  },
  {
    id: "4",
    title: "Elegant Waterfront Duplex",
    location: "Dubai Marina, Dubai",
    price: 1250000,
    type: "Duplex",
    status: "sale",
    bedrooms: 6,
    bathrooms: 5,
    area: 5200,
    featured: true,
    image: "/images/image4.jpg",
    description:
      "Luxury waterfront duplex with private parking, rooftop terrace, and ",
  },
  {
    id: "5",
    title: "Urban Studio Apartment",
    location: "Paris, France",
    price: 1200,
    type: "Studio",
    status: "rent",
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    featured: false,
    image: "/images/image5.jpg",
    description:
      "Compact and stylish studio apartment perfect for young professionals",
  },
  {
    id: "6",
    title: "Premium Penthouse Suite",
    location: "London, United Kingdom",
    price: 2500000,
    type: "Penthouse",
    status: "sale",
    bedrooms: 5,
    bathrooms: 6,
    area: 6800,
    featured: true,
    image: "/images/image6.jpg",
    description:
      "Exclusive penthouse suite with panoramic ocean views, luxury ameniti",
  },
];
